version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
      - image: 'circleci/mongo:latest'
    steps:
      - checkout
      - run:
          name: Install npm Dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run test
workflows:
  build_test:
    jobs:
      - run_tests
