/**
 * K6 Post Creation & Fanout Load Test
 * Tests post creation and validates fanout to followers' feeds
 */

import http from 'k6/http';
import { check, group, sleep } from 'k6';
import { SharedArray } from 'k6/data';
import { config, getLoadTestOptions } from '../config.js';
import {
  authenticatedRequest,
  checkResponse,
  parseJSON,
  randomSleep,
  generatePostContent,
  generateHashtags,
  postCreationTime,
  feedLoadTime,
  postsCreated,
  errorRate
} from '../utils.js';

export let options = getLoadTestOptions();

// Load seeded users data (should be generated by seed script)
const users = new SharedArray('users', function () {
  // In production, load from seed data file
  // For now, use env or generate
  const userCount = parseInt(__ENV.USER_COUNT) || 10;
  const seedUsers = [];

  // This assumes seed script has run and created users
  // In real scenario, load from seed output JSON
  for (let i = 0; i < userCount; i++) {
    seedUsers.push({
      email: `testuser${i}@unilag.edu.ng`,
      password: 'Test@123',
      token: null,
      userId: null
    });
  }

  return seedUsers;
});

let authenticatedUsers = [];

export function setup() {
  console.log('='.repeat(60));
  console.log('POST FANOUT TEST - Create Posts & Validate Feed Distribution');
  console.log('='.repeat(60));
  console.log(`Base URL: ${config.baseUrl}`);
  console.log(`Users: ${users.length}`);
  console.log('');

  // Login all users first
  console.log('📝 Logging in test users...');
  const baseUrl = config.baseUrl;

  for (const user of users) {
    const loginRes = http.post(
      `${baseUrl}/api/v1/users/login`,
      JSON.stringify({
        email: user.email,
        password: user.password
      }),
      {
        headers: { 'Content-Type': 'application/json' }
      }
    );

    if (loginRes.status === 201) {
      const body = JSON.parse(loginRes.body);
      authenticatedUsers.push({
        email: user.email,
        token: body.token,
        userId: body.user._id || body.user.id
      });
    }
  }

  console.log(`✅ Logged in ${authenticatedUsers.length} users\n`);

  return { users: authenticatedUsers };
}

export default function (data) {
  const baseUrl = config.baseUrl;

  if (!data || !data.users || data.users.length === 0) {
    console.error('No authenticated users available');
    return;
  }

  // Pick random user
  const user = data.users[__VU % data.users.length];

  group('create_post', () => {
    const content = generatePostContent();
    const hashtags = generateHashtags();

    const createPayload = {
      content,
      hashtags,
      media: [] // No media for load test
    };

    const startTime = Date.now();
    const createRes = authenticatedRequest(
      http,
      'post',
      `${baseUrl}/api/v2/posts/create`,
      user.token,
      createPayload
    );
    const duration = Date.now() - startTime;

    const success = check(createRes, {
      'create_post: status is 200 or 201': (r) => r.status === 200 || r.status === 201,
      'create_post: has post data': (r) => {
        const body = parseJSON(r);
        return body && (body.post || body.data);
      }
    });

    errorRate.add(!success);
    postCreationTime.add(duration);

    if (success) {
      postsCreated.add(1);
    } else {
      console.warn(`Post creation failed: ${createRes.status}`);
    }

    randomSleep(2, 4);
  });

  group('check_newsfeed', () => {
    // Validate post appears in followers' feeds
    const startTime = Date.now();
    const feedRes = authenticatedRequest(
      http,
      'get',
      `${baseUrl}/api/v2/posts/newsfeed?page=1&limit=20`,
      user.token
    );
    const duration = Date.now() - startTime;

    const success = check(feedRes, {
      'newsfeed: status is 200': (r) => r.status === 200,
      'newsfeed: has posts': (r) => {
        const body = parseJSON(r);
        return body && body.posts && body.posts.length > 0;
      },
      'newsfeed: loads within 500ms': (r) => duration < 500
    });

    errorRate.add(!success);
    feedLoadTime.add(duration);

    if (!success) {
      console.warn(`Newsfeed load failed: ${feedRes.status}`);
    }

    randomSleep(3, 5);
  });

  group('poll_newsfeed', () => {
    // Test real-time polling for new posts
    const pollRes = authenticatedRequest(
      http,
      'get',
      `${baseUrl}/api/v2/posts/newsfeed/poll?lastPostId=000000000000000000000000`,
      user.token
    );

    const success = check(pollRes, {
      'poll: status is 200': (r) => r.status === 200,
      'poll: response time < 300ms': (r) => r.timings.duration < 300
    });

    errorRate.add(!success);

    randomSleep(1, 2);
  });
}

export function teardown(data) {
  console.log('\n' + '='.repeat(60));
  console.log('✅ POST FANOUT TEST COMPLETE');
  console.log('='.repeat(60));
  console.log('');
  console.log('📊 Key Metrics:');
  console.log('  - Posts created: Check summary for count');
  console.log('  - Post creation p95: Check summary');
  console.log('  - Feed load p95: Check summary');
  console.log('');
}
