import { InterestRepository } from '../../repositories/InterestRepository';
import { UserRepository } from '../../repositories/UserRepository';
import { NotFoundError, ValidationError, AppError } from '../../errors';
import { User } from '../../entities/User';
import { botTypes } from '../../types/types';

export class UsersService {
  private interestRepository: InterestRepository;
  private userRepository: UserRepository;

  constructor() {
    this.interestRepository = new InterestRepository();
    this.userRepository = new UserRepository();
  }

  async getInterests() {
    const categories = await this.interestRepository.getAllCategories();

    return {
      data: {
        categories: categories.map(cat => ({
          id: cat.id,
          name: cat.name,
          icon: cat.icon,
          emoji: cat.emoji,
          displayOrder: cat.displayOrder,
          topics: cat.topics
        }))
      },
      meta: {
        maxSelectableTopics: 3
      }
    };
  }

  /**
   * Get current user profile
   */
  async getCurrentUser(userId: string) {
    const user = await this.userRepository.findByIdSecure(userId);

    if (!user) {
      throw new NotFoundError('User not found');
    }

    return {
      data: {
        id: user._id,
        name: user.name,
        userTag: user.userTag,
        email: user.email,
        userProfile: user.userProfile,
        fcm_token: user.fcm_token,
        createdAt: user.createdAt,
        updatedAt: user.updatedAt
      }
    };
  }

  /**
   * Update user profile
   */
  async updateProfile(userId: string, profileData: any) {
    const updateData: any = {};

    // Map fields to userProfile nested structure
    if (profileData.name) updateData.name = profileData.name;
    if (profileData.bio !== undefined) updateData['userProfile.bio'] = profileData.bio;
    if (profileData.university !== undefined) updateData['userProfile.university'] = profileData.university;
    if (profileData.course !== undefined) updateData['userProfile.course'] = profileData.course;
    if (profileData.gender !== undefined) updateData['userProfile.gender'] = profileData.gender;
    if (profileData.level !== undefined) updateData['userProfile.level'] = profileData.level;
    if (profileData.phoneNumber !== undefined) updateData['userProfile.phoneNumber'] = profileData.phoneNumber;

    const updatedUser = await this.userRepository.updateProfile(userId, updateData);

    if (!updatedUser) {
      throw new NotFoundError('Failed to update user profile');
    }

    return {
      data: {
        id: updatedUser._id,
        name: updatedUser.name,
        userTag: updatedUser.userTag,
        email: updatedUser.email,
        userProfile: updatedUser.userProfile,
        updatedAt: updatedUser.updatedAt
      },
      message: 'Profile updated successfully'
    };
  }

  /**
   * Save user interests
   */
  async saveInterests(userId: string, topicIds: string[]) {
    // Validate that topic IDs exist
    const categories = await this.interestRepository.getAllCategories();
    const allTopicIds = categories.flatMap(cat => cat.topics.map(topic => topic.id));
    console.log(allTopicIds)

    const invalidTopics = topicIds.filter(id => !allTopicIds.includes(id));
    if (invalidTopics.length > 0) {
      throw new ValidationError('Invalid topic IDs', { invalidTopics });
    }

    const updatedUser = await this.userRepository.saveInterests(userId, topicIds);

    if (!updatedUser) {
      throw new AppError('Failed to save interests', 500);
    }

    return {
      data: {
        interests: updatedUser.userProfile.interests
      },
      message: 'Interests saved successfully'
    };
  }

  /**
   * Seed bot accounts at startup
   */
  async seedBots() {
    // Helper to capitalize first letter
    const capitalize = (str: string) => str.charAt(0).toUpperCase() + str.slice(1);

    // Dynamically create bot configs from botTypes array
    for (const botType of botTypes) {
      const config = {
        botType,
        name: `CampusX ${capitalize(botType)} Bot`,
        userTag: `campusx_${botType}_bot`,
        email: `campusx-${botType}-bot@campusx.com`,
        bio: `Your automated source for ${botType} updates`
      };

      // Check if bot already exists
      const existingUser = await this.userRepository.findByEmail(config.email);

      if (existingUser) {
        console.log(`✓ Bot ${config.botType} already exists. Skipping...`);
        continue;
      }

      // Create user account via v1 method
      const userObject = {
        name: config.name,
        userTag: config.userTag,
        email: config.email,
        password: `bot_${config.botType}_${Date.now()}`, // Random password
        userProfile: {
          bio: config.bio,
          gender: 'other',
          university: 'CampusX System',
          avatar: null // Will be auto-generated by Gravatar
        },
        accountType: 'bot',
        botMetadata: {
          botType: config.botType,
          createdBy: 'system',
          version: '1.0'
        }
      } as any;

      const result = await User.CreateUser(userObject);

      if (result.exists) {
        console.log(`✗ Failed to create ${config.botType} bot: ${result.err_message}`);
      } else {
        console.log(`✓ Successfully created ${config.botType} bot account`);
      }
    }
  }
}
